name: Deploy to shinyapps.io

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.0'
      
      - name: Install rsconnect package
        run: |
          install.packages("rsconnect", repos = "https://cloud.r-project.org")
        shell: Rscript {0}
      
      - name: Install Shiny package
        run: |
          install.packages("shiny", repos = "https://cloud.r-project.org")
        shell: Rscript {0}
      
      - name: Configure rsconnect
        env:
          SHINYAPPS_NAME: ${{ secrets.SHINYAPPS_NAME }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          rsconnect::setAccountInfo(
            name   = Sys.getenv("SHINYAPPS_NAME"),
            token  = Sys.getenv("SHINYAPPS_TOKEN"),
            secret = Sys.getenv("SHINYAPPS_SECRET")
          )
        shell: Rscript {0}
      
      - name: Deploy to shinyapps.io
        env:
          SHINYAPPS_NAME: ${{ secrets.SHINYAPPS_NAME }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          rsconnect::deployApp(
            appDir = ".",
            appName = "my-first-r-project",
            account = Sys.getenv("SHINYAPPS_NAME"),
            forceUpdate = TRUE
          )
        shell: Rscript {0}
